### ISSUE TITLE
Please allow custom setting of UIViewController to present email view on iOS

### ISSUE THREAD

**Issue by ellisnet** [cjlotz/Xamarin.Plugins#44] opened 2016-10-27 16:41 UTC
It appears that there has been work to fix a problem on iOS where a call to `CrossMessaging.Current.EmailMessenger.SendEmail()` was failing and producing: `Warning: Attempt to present <MFMailComposeViewController> whose view is not in the window hierarchy!` - as discussed in closed issue #24 
However, I am using version 3.2.1 of the Xam.Plugins.Messaging NuGet package, and still encountering this issue - please see: [http://stackoverflow.com/questions/40273884/how-to-reset-prism-for-xamarin-forms-view-navigation-stack](http://stackoverflow.com/questions/40273884/how-to-reset-prism-for-xamarin-forms-view-navigation-stack)
I have gotten around this problem by modifying the MessagingExtensions class in Plugin.Messaging.iOSUnified, as follows:

```
    private static UIViewController _messagingViewController = null;
    private static readonly object messagingControllerLocker = new object();

    public static void SetMessagingViewController(UIViewController controller)
    {
        lock (messagingControllerLocker)
        {
            _messagingViewController = controller;
        }
    }

    public static void PresentUsingRootViewController(this UIViewController controller)
    {
        if (controller == null)
            throw new ArgumentNullException(nameof(controller));

        UIViewController visibleViewController = null;

        lock (messagingControllerLocker)
        {
            visibleViewController = _messagingViewController;
            _messagingViewController = null;
        }

        visibleViewController = visibleViewController ?? GetVisibleViewController(null);
        if (visibleViewController == null)
        {
            throw new InvalidOperationException("Could not find a visible UIViewController on the Window hierarchy");
        }
        visibleViewController.PresentViewController(controller, true, () => { });
    }
```

So now I call `SetMessagingViewController()` with a UIViewController that I have created just before I call `SendMail()`, but that feels like kludge; and I would like to migrate away from my custom version of the Plugin.Messaging.iOSUnified library... 

Can you add a supported way of doing this?

**Comment by dylanberry** [comment] 2016-11-07 19:34
@cjlotz I pinged you on twitter earlier with a general behaviour question, this is what I'm running into, the mail client doesn't appear and this message is logged in the application output window:

> Warning: Attempt to present &lt;MFMailComposeViewController: 0x14d142e00&gt; on &lt;Xamarin_Forms_Platform_iOS_PageRenderer: 0x14ddbb820&lt; whose view is not in the window hierarchy!

CC: @JasonHardman as he resolved #24

**Comment by dylanberry** [comment] 2016-11-07 21:10
Alright, I have a workaround for this issue. I'm using Xamarin.Forms and Prism in my app. The iOS version of my app was using a relative uri in the Prism navigation service, I was able to alleviate this by switching to an absolute uri. I don't know how the Prism navigation service works, but it appears that when using a relative uri, there are issues determining the current view.

@ellisnet the stackoverflow link you posted was extremely helpful and directly applicable to my case, thank you for that.

**Comment by cjlotz** [comment] 2017-03-20 14:32
@ellisnet @dylanberry I'm not a Prism user, so after reading through the issue is this still a problem based on the work arounds mentioned?

**Comment by cjlotz** [comment] 2017-04-06 20:55
Closing due to lack of further feedback

**Closed by cjlotz** 2017-04-06 20:55 UTC
