### ISSUE TITLE
Text, keyboard and send button quickly disappear after calling SendSms

### ISSUE THREAD

**Issue by mwerickson** [cjlotz/Xamarin.Plugins#39] opened 2016-09-14 20:28 UTC
When I execute the following code:

```
var smsTask = MessagingPlugin.SmsMessenger;
if (smsTask.CanSendSms)
{
    smsTask.SendSms(phoneNumber, textToSend);
}
else
{
    Debug.WriteLine($"Unable to text {phoneNumber} - Cannot send SMS text at this time");
}
```

The text dialog is showing, the correct number is in the "To" area, and the text is placed in the text area, however VERY quickly the text area and the keyboard (including the send button) go away.  We used slo-mo video to capture that the text WAS indeed passed to the text app and that it all went away, leaving the dialog just sitting there with the number and a cancel button.

Any ideas what could be causing this?

Running XForms 2.3.1.114
Xam.Plugins.Messaging 3.2.1

hardware is iPad Air 2 (but can duplicate on iPad mini) both running iOS 9.3.5
And it works fine on iPhones

Thanks for any help!

**Comment by cjlotz** [comment] 2017-04-05 07:22
Cannot reproduce this on my side.  Is this still an issue?

**Comment by cjlotz** [comment] 2017-04-08 13:21
Closing issue - no further feedback

**Closed by cjlotz** 2017-04-08 13:21 UTC
