### ISSUE TITLE
Doesn't Work on First Launch of App

### ISSUE THREAD

**Issue by kartiksolanki** [cjlotz/Xamarin.Plugins#69] opened 2017-10-22 00:45 UTC
Hi, I have used this plugin in my Xamarin.Forms project and I have found one issue. This plugin doesn't work on the first launch of my app downloaded from the store but when I restart the app, the functionality works like a charm. Any idea what can be the reason?

**Comment by kartiksolanki** [comment] 2017-10-22 04:46
The debug log says - "Warning: Attempt to present <MFMessageComposeViewController: 0x103733200> on <Xamarin_Forms_Platform_iOS_ModalWrapper: 0x10b33ebe0> whose view is not in the window hierarchy!"

**Comment by cjlotz** [comment] 2017-11-04 18:27
Duplicate of #72

**Closed by cjlotz** 2017-11-04 18:27 UTC
