### ISSUE TITLE
Cannot attach a file to GMail for Android with Xamarin.forms

### ISSUE THREAD

**Issue by lanarchyste** [cjlotz/Xamarin.Plugins#88] opened 2018-01-26 09:10 UTC
Hello,

I use the SimpleLogger plugin to create log files. Files are created in the `/data/user/0/[PACKAGE_NAME]/files/.config/[NAME].log` directory

So I added the following paths in file file_paths.xml: 
`<files-path name = "internal_files" path = "." />`

I know that my configuration is supported because if I remove this path, I get an error of type: 
`Failed to find configured root which contains /data/data/com.agilitic.kibati/files/.config/kibati_log1. log`

But when I want to send an email, Gmail tells me the following error: 
`Permission denied for the attachment`

I tried in PCL and Android.

I am using version 5.0.0 of the plugin, and my Android project use the target API26

Do I forget a setting?

Thanks

Best Regards

Julien

**Comment by MikaTml** [comment] 2018-02-13 07:32
Hi

Same issue. Attachment works with iOS but not with Android.

`02-13 09:30:27.092 15430-15430/PACKAGE_NAME_REPLACED I/mono-stdout: File location: /data/user/0/PACKAGE_NAME_REPLACED/files/FILE_NAME.pdf
02-13 09:30:27.094 15430-15430/PACKAGE_NAME_REPLACED D/Mono: Assembly Ref addref Plugin.Messaging[0xe745b360] -> System.Core[0xe745cda0]: 10
02-13 09:30:27.097 15430-15430/PACKAGE_NAME_REPLACED D/Mono: Assembly Ref addref Plugin.Messaging[0xe745b360] -> Xamarin.Android.Support.Core.Utils[0xe745bde0]: 3
02-13 09:30:27.159 15430-15430/PACKAGE_NAME_REPLACED D/InputMethodManager: HSI from window - flag : 0 Pid : 15430
02-13 09:30:27.230 15430-15430/PACKAGE_NAME_REPLACED D/ViewRootImpl@350d4df[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0
02-13 09:30:27.298 15430-15430/PACKAGE_NAME_REPLACED D/ViewRootImpl@350d4df[MainActivity]: mHardwareRenderer.destroy()#1
02-13 09:30:27.305 15430-15430/PACKAGE_NAME_REPLACED D/ViewRootImpl@350d4df[MainActivity]: Relayout returned: oldFrame=[0,0][1200,1920] newFrame=[0,0][1200,1920] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
02-13 09:30:28.577 15430-15430/PACKAGE_NAME_REPLACED D/InputTransport: Input channel destroyed: fd=69
02-13 09:30:28.947 15430-15454/PACKAGE_NAME_REPLACED D/Mono: Assembly Ref addref Xamarin.Forms.Platform.Android[0xe745c7a0] -> System.Runtime.Serialization[0xcdcdede0]: 3
02-13 09:30:28.947 15430-15454/PACKAGE_NAME_REPLACED D/Mono: Assembly Ref addref System.Runtime.Serialization[0xcdcdede0] -> System.Xml[0xe745d820]: 5
02-13 09:30:28.996 15430-15454/PACKAGE_NAME_REPLACED D/Mono: Assembly Ref addref System.Runtime.Serialization[0xcdcdede0] -> System[0xe745d640]: 13
02-13 09:30:29.010 15430-15454/PACKAGE_NAME_REPLACED D/Mono: Image addref System.ServiceModel.Internals[0xc93622a0] -> System.ServiceModel.Internals.dll[0xcce4b300]: 2
02-13 09:30:29.010 15430-15454/PACKAGE_NAME_REPLACED D/Mono: Prepared to set up assembly 'System.ServiceModel.Internals' (System.ServiceModel.Internals.dll)
02-13 09:30:29.011 15430-15454/PACKAGE_NAME_REPLACED D/Mono: Assembly System.ServiceModel.Internals[0xc93622a0] added to domain RootDomain, ref_count=1
02-13 09:30:29.013 15430-15454/PACKAGE_NAME_REPLACED D/Mono: AOT: image 'System.ServiceModel.Internals.dll.so' not found: dlopen failed: library "/data/app/PACKAGE_NAME_REPLACED-1/lib/arm/libaot-System.ServiceModel.Internals.dll.so" not found
02-13 09:30:29.013 15430-15454/PACKAGE_NAME_REPLACED D/Mono: AOT: image '/usr/local/lib/mono/aot-cache/arm/System.ServiceModel.Internals.dll.so' not found: dlopen failed: library "/data/app/PACKAGE_NAME_REPLACED-1/lib/arm/libaot-System.ServiceModel.Internals.dll.so" not found
02-13 09:30:29.013 15430-15454/PACKAGE_NAME_REPLACED D/Mono: Config attempting to parse: 'System.ServiceModel.Internals.dll.config'.
02-13 09:30:29.014 15430-15454/PACKAGE_NAME_REPLACED D/Mono: Config attempting to parse: '/usr/local/etc/mono/assemblies/System.ServiceModel.Internals/System.ServiceModel.Internals.config'.
02-13 09:30:29.014 15430-15454/PACKAGE_NAME_REPLACED D/Mono: Assembly Ref addref System.Runtime.Serialization[0xcdcdede0] -> System.ServiceModel.Internals[0xc93622a0]: 2
02-13 09:30:29.014 15430-15454/PACKAGE_NAME_REPLACED D/Mono: Assembly Ref addref System.ServiceModel.Internals[0xc93622a0] -> mscorlib[0xebac8d60]: 61
02-13 09:30:29.014 15430-15454/PACKAGE_NAME_REPLACED D/Mono: Assembly Ref addref System.ServiceModel.Internals[0xc93622a0] -> System.Xml[0xe745d820]: 6
02-13 09:30:29.298 15430-15454/PACKAGE_NAME_REPLACED D/Mono: Assembly Ref addref System.ServiceModel.Internals[0xc93622a0] -> System[0xe745d640]: 14
02-13 09:30:29.367 15430-15459/PACKAGE_NAME_REPLACED D/Mono: Assembly Ref addref Xamarin.Forms.Platform.Android[0xe745c7a0] -> System.Xml[0xe745d820]: 7`

Is this what you wanted @prashantvc ?

**Comment by cjlotz** [comment] 2018-02-20 19:27
@lanarchyste did you try `<files-path name = "internal_files" path = ".config/" />`

**Comment by cprice70** [comment] 2018-03-24 22:09
Had this same problem and the problem is that Gmail 5.0 has added security checks.  This link tells more about it 
https://stackoverflow.com/questions/26883259/gmail-5-0-app-fails-with-permission-denied-for-the-attachment-when-it-receives

**Comment by cjlotz** [comment] 2018-04-02 18:28
As evident in the link posted by @cprice70 , this is not an issue with the plugin logic itself, but a security requirement implemented in Gmail for adding file attachments to an e-mail. I'm therefore closing the issue.  Refer to the link for how people solve the issue.  Best approach seems to be attaching files from external storage using content provider and content uri's.

**Closed by cjlotz** 2018-04-02 18:28 UTC
Labels: need-more-info

**Comment by cjlotz** [comment] 2018-04-02 18:30
I've created a [separate issue](#96) to rework the sample logic using a content provider at a later stage.
